---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache,git on ubuntu
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - apache2
        - git
      when: ansible_distribution == 'Ubuntu'
  
    - name: install apache server on Linux
      yum:
        name: "{{item}}"
        state: present
      with_items:
          - httpd
          - git
      when: ansible_distribution == 'RedHat'
    - name: start apache server and enable
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'RedHat'
    - name: start apache server and enable
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'
    - name: deploy website on to apache by cloning from git
      git:
        repo: https://github.com/javahometech/javahome-app
        dest: /var/www/html/
